services:
  # MySQL на сервере уже установлена (не запускаем в Docker)
  # В .env используйте: DATABASE_URL="mysql://user:password@172.17.0.1:3306/psychotest_production"
  # 172.17.0.1 - это IP хоста из Docker контейнера

  # Основное приложение
  psychotest:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Доступ к MySQL на хосте
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx как обратный прокси
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-docker.conf:/etc/nginx/conf.d/default.conf
      - letsencrypt:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    depends_on:
      - psychotest
    restart: unless-stopped

  # Мониторинг с Watchtower (автообновление)
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
    restart: unless-stopped

volumes:
  letsencrypt:
  certbot-webroot:
